services:
  nvim:
    build: .
    container_name: nvim-jiri
    volumes:
      - ./nvim:/root/.config/nvim
      - ./:/workspace
      - /run/user/1000:/run/user/1000
    working_dir: /workspace
    tty: true
    environment:
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
    entrypoint: ["/bin/sh", "-c", "nvim"]
